# Generated by Django 2.1.7 on 2019-08-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190804_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
