# Generated by Django 2.1.7 on 2019-08-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190804_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('동양풍', '동양풍'), ('서양풍', '서양풍'), ('고전', '고전'), ('현대', '현대')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('여성', '여성'), ('남성', '남성')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
