# Generated by Django 2.1.7 on 2019-08-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190804_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('동양풍', '동양풍'), ('서양풍', '서양풍'), ('고전', '고전'), ('현대', '현대')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('여성', '여성'), ('남성', '남성')], max_length=2, null=True),
        ),
    ]
