# Generated by Django 2.1.7 on 2019-08-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190804_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('동양풍', '동양풍'), ('서양풍', '서양풍'), ('고전', '고전'), ('현대', '현대')], max_length=3, null=True),
        ),
    ]
