# Generated by Django 2.1.7 on 2019-08-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190804_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('여성', '여성'), ('남성', '남성')], max_length=2, null=True)),
                ('category', models.CharField(choices=[('동양풍', '동양풍'), ('서양풍', '서양풍'), ('고전', '고전'), ('현대', '현대')], max_length=3, null=True)),
            ],
        ),
    ]
