# Generated by Django 2.1.7 on 2019-08-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='text',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
